spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:url_shortener;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    baseline-on-migrate: true
