services:
  db:
    image: mysql:8
    container_name: url-shortener-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - url-shortener-db-volume:/var/lib/mysql
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: Asia/Seoul

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - private

  # 아래는 예시
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: server
    restart: always
    ports:
      - "5000:8089"
    networks:
      - private
      - lb
    environment:
      DB_USERNAME: mysql_user
      DB_PASSWORD: mysql_password
      DB_HOST: url-shortener-db
      DB_PORT: 3306
      DB_NAME: url_shortener
      REDIS_HOST: url-shortener-redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:3000
      HASHID_SALT: 138431694131434341
      HASHID_ROUND: 6

  frontend:
    build:
      context: ../frontend
      args:
        BACKEND_URL: http://localhost:5000
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - lb

volumes:
  url-shortener-db-volume:

networks:
  private:
  lb:
